import time
import random

rltList = [
    'Loading...',
    'Hold Up...',
    'Getting the ammo...',
    'Putting down inconveniences...',
    '( -_•)▄︻テحكـ━一...',
    'gun  ̸̇̎/̸̄̿̅̎̎̅͆ ͆͆͆͆̔̿͞ ͆̅̿̄͞ ̿ ̄̇̿̚ ̎ ̎͆ ...',
    ':)...',
    'BIG CHUNGUS...',
    'Beans...',
    'The heavy is dead (˚0˚)...',
    'G was here...',
    'Sending carrier pigeons...',
    'Spawning sarcasm...',
    'Adjusting the flux capacitor...',
    'Downloading more RAM...',
    'Waiting for the dinosaurs to return...',
    'Making a sandwich...',
    'Summoning memes...',
    'Catching some Zs...',
    'Serving up fresh pixels...',
    'Teleporting bread...',
    'Brb, coffee break...',
    'Mining for bitcoins...',
    'Feeding the hamsters...',
    'Enabling god mode...',
    'Avoiding awkward small talk...',
    'Inserting cheesy joke...',
    'Ordering pizza...',
    'Building sandcastles...',
    'Cleaning up the internet...',
    'Barking at the server...',
    'Charging lazers...',
    'Spinning in circles...',
    'Testing gravity...',
    'Searching for meaning...',
    'Doing a little dance...',
    'Trying to find Waldo...',
    'Calling tech support...',
    'Moving some bytes...',
    'Crawling through the code...',
    'Baking cookies...',
    'Pressing random buttons...',
    'Testing the patience algorithm...',
    'Channeling Bob Ross...',
    'Clearing traffic jams...',
    'Calibrating personality...',
    'Rolling dice...',
    'Polishing the pixels...',
    'Reading the fine print...',
    'Unlocking the secrets...',
    'Poking the server...',
    'Watering the code...',
    'Making the impossible possible...',
    'Shuffling the data...',
    'Dealing with the gremlins...',
    'Tuning the algorithm...',
    'Sending virtual hugs...',
    'Feeding the virtual pets...',
    'Assembling the team...',
    'Counting stars...',
    'Sending love letters...',
    'Translating the bytes...',
    'Preparing the magic...',
    'Lifting the fog...',
    'Spinning up the engine...',
    'Searching for lost time...',
    'Untangling the web...',
    'Wrestling with bugs...',
    'Plucking the strings...',
    'Singing a lullaby...',
    'Fluffing the clouds...',
    'Training the algorithm...',
    'Chasing rainbows...',
    'Whistling a happy tune...',
    'Polishing the code...',
    'Mending the gaps...',
    'Getting the band back together...',
    'Launching confetti...',
    'Taming the wild variables...',
    'Baking virtual pies...',
    'Scribbling on the chalkboard...',
    'Transcending dimensions...',
    'Catching the last train...',
    'Finding the perfect meme...',
    'Refilling the ink...',
    'Adjusting the spotlight...',
    'Breaking the fourth wall...',
    'Harmonizing the bits...',
    'Patching the holes...',
    'Cracking the code...',
    'Playing hide and seek...',
    'Unleashing the creativity...',
    'Conducting the orchestra...',
    'Feeding the cosmic machine...',
    'Getting the jokes in line...',
    'Caring for the bytes...',
    'Throwing a digital party...',
    'Drawing the curtains...',
    'Blowing up balloons...',
    'Lighting up the fireworks...',
    'Spinning the wheel of fortune...',
    'Filling the virtual tank...',
    'Creating digital magic...',
    'Shaking the pixels...',
    'Unwrapping the gift...',
    'Bringing the code to life...',
    'Greasing the wheels...',
    'Drumming up excitement...',
    'Tickling the algorithm...',
    'Spinning the web...',
    'Weaving the story...',
    'Stirring the code...',
    'Brushing off the dust...',
    'Polishing the interface...',
    'Finding the lost key...',
    'Hunting for Easter eggs...',
    'Setting the stage...',
    'Climbing the virtual ladder...',
    'Turning the dials...',
    'Finding the missing piece...',
    'Making the magic happen...',
    'Building the dream...',
    'Catching the last pixel...',
    'Unveiling the secret...',
    'Riding the rollercoaster...',
    'Making it shine...',
    'Tuning the frequencies...',
    'Warming up the circuits...',
    'Whipping up some magic...',
    'Shaking off the bugs...',
    'Paddling through code...',
    'Inflating the pixels...',
    'Cooking up a storm...',
    'Turning up the volume...',
    'Arranging the stars...',
    'Sorting the data...',
    'Scrambling the bytes...',
    'Merging the pieces...',
    'Bridging the gaps...',
    'Hatching the plan...',
    'Spinning the threads...',
    'Brewing up some fun...',
    'Pepe the Frog is watching...',
    'Doge is cheering you on...',
    'Distracted Boyfriend is busy...',
    'Kermit is sipping tea...',
    'Grumpy Cat is unimpressed...',
    'Nyan Cat is in space...',
    'Hide the Pain Harold is hiding...',
    'Arthur’s Fist is clenched...',
    'Expanding Brain is expanding...',
    'Rickrolling in progress...',
    'Success Kid is high-fiving...',
    'Mocking SpongeBob is mocking...',
    'Confused Nick Young is confused...',
    'Is this a pigeon? Yes...',
    'Drake Hotline Bling is uninterested...',
    'How About No is refusing...',
    'Overly Attached Girlfriend is waiting...',
    'Wojak is Wojacking...',
    'Roll Safe is thinking...',
    'Inhaling Seagull is flying...',
    'Kermit is plotting...',
    'DogeCoin to the moon...',
    'Philosoraptor is pondering...',
    'All the Feels...',
    'Trollface is trolling...',
    'Success Kid says thanks...',
    'C9 was here',
    '>>>JOE BIDEN<<<...',
    'Just a few more moments...',
    'Preparing the cosmic alignment...',
    'Recalibrating the universe...',
    'Harnessing the power of memes...',
    'Synchronized with the stars...',
    'Waiting for the code to catch up...',
    'Finding the right frequency...',
    'Unlocking the digital vault...',
    'Aligning the pixels...',
    'Balancing the data streams...',
    'Feeding the algorithm...',
    'Summoning virtual spirits...',
    'Injecting some magic...',
    'Configuring the matrix...',
    'Dusting off the virtual shelves...',
    'Creating pixel-perfect harmony...',
    'Juggling the variables...',
    'Polishing the interface...',
    'Synchronizing the timelines...',
    'Casting a digital spell...',
    'Waking up the servers...',
    'Adding a touch of sparkle...',
    'Tuning the virtual orchestra...',
    'Preparing the pixelated party...',
    'Refining the digital experience...',
    'Elevating the code...',
    'Crafting the perfect pixel...',
    'Optimizing the algorithm...',
    'Bridging the digital divide...',
    'Launching into hyperspace...',
    'Aligning the code fragments...',
    'Setting up the virtual stage...',
    'Warming up the circuits...',
    'Brewing up some algorithmic magic...',
    'Tuning the virtual soundscape...',
    'Conducting the digital symphony...',
    'Preparing for launch...',
    'Crafting the ultimate meme...',
    'Fine-tuning the experience...',
    'Loading the magic...',
    'Synchronizing the elements...',
    'Adjusting the virtual compass...',
    'Molding the perfect pixel...',
    'Aligning the digital forces...',
    'Perfecting the virtual reality...',
    'Summoning the code wizards...'
]

def randomLoadingText(amount, minTime, maxTime, console):
    for i in range(amount):
        time.sleep(random.randint(minTime, maxTime))
        yield random.choice(rltList)

#for message in randomLoadingText(7, 1, 4, 'pc'): #test
#    print(message)  


fake_hacking_prompts = [
    "Establishing secure connection to remote server...",
    "Bypassing firewall security protocols...",
    "Injecting SQL payload into vulnerable database...",
    "Cracking 128-bit AES encryption...",
    "Decrypting intercepted data packets...",
    "Compiling exploit for buffer overflow vulnerability...",
    "Scanning network for open ports and vulnerabilities...",
    "Brute-forcing admin login credentials...",
    "Executing privilege escalation to obtain root access...",
    "Installing keylogger on target system...",
    "Spoofing MAC address to bypass network restrictions...",
    "Retrieving hashed passwords from compromised database...",
    "Initiating DDoS attack on target IP address...",
    "Uploading malware to target server...",
    "Exfiltrating confidential data from secured directory...",
    "Disabling security cameras and system logs...",
    "Evading detection by anti-virus software...",
    "Erasing all traces from server logs...",
    "Decrypting SSH key to gain access to remote machine...",
    "Dumping memory contents for analysis...",
    "Analyzing vulnerability in server's authentication system...",
    "Injecting reverse shell payload into server process...",
    "Decrypting intercepted VPN traffic...",
    "Phishing for credentials via compromised email...",
    "Bypassing two-factor authentication...",
    "Mapping network topology of target organization...",
    "Creating rogue access point to intercept traffic...",
    "Infiltrating dark web marketplaces for intel...",
    "Analyzing blockchain transactions for vulnerabilities...",
    "Modifying DNS records to redirect traffic...",
    "Monitoring real-time network traffic...",
    "Cloning RFID tags for unauthorized access...",
    "Fuzzing application input for hidden vulnerabilities...",
    "Exploiting zero-day vulnerability in software...",
    "Overwriting MBR to prevent system boot...",
    "Hijacking session tokens for admin privileges...",
    "Scraping social media for user metadata...",
    "Exploiting XSS vulnerability to inject malicious scripts...",
    "Intercepting and decrypting SSL/TLS communication...",
    "Modifying registry keys to maintain persistence...",
    "Compromising IoT devices on the network...",
    "Setting up remote access backdoor...",
    "Scanning for outdated software versions with known exploits...",
    "Executing ransomware payload on target system...",
    "Simulating a breach through VPN tunneling...",
    "Listening in on encrypted VoIP communications...",
    "Spoofing DNS responses for man-in-the-middle attack...",
    "Encrypting local files for ransomware demands...",
    "Cross-referencing hashes with known breaches...",
    "Planting a trojan horse in the boot sector...",
    "Escalating network traffic for packet sniffing...",
    "Bypassing SSL pinning to access hidden APIs...",
    "Compromising SSL certificates for MITM attacks...",
    "Exfiltrating session cookies from browser storage...",
    "Using steganography to hide payload in images...",
    "Manipulating system clocks to bypass time-sensitive security...",
    "Overclocking system to induce hardware failure...",
    "Simulating fake software updates to trick users...",
    "Performing memory scraping on POS systems...",
    "Launching a rainbow table attack on password hashes...",
    "Decrypting proprietary data formats...",
    "Modifying software binaries to include backdoor...",
    "Compiling code from leaked source to find vulnerabilities...",
    "Exploiting unpatched CVEs for immediate access...",
    "Utilizing deep packet inspection for targeted attacks...",
    "Reverse engineering software to disable DRM...",
    "Hijacking Bluetooth devices for data theft...",
    "Creating botnet for distributed attack...",
    "Capturing and replaying API requests for exploitation...",
    "Overloading database with malicious queries...",
    "Analyzing cold-boot attack results...",
    "Deploying rootkit to maintain permanent system access...",
    "Decrypting files with brute-force methods...",
    "Sniffing unsecured FTP and Telnet traffic...",
    "Bypassing file permission restrictions on secured systems...",
    "Poisoning ARP cache to redirect network traffic...",
    "Intercepting public key exchange for eavesdropping...",
    "Initiating packet injection into wireless network...",
    "Analyzing side-channel attacks to gather sensitive data...",
    "Cross-site request forgery (CSRF) exploitation in progress...",
    "Infiltrating wireless mesh network for control...",
    "Decoding base64 encoded payloads...",
    "Automating brute force attacks on weak passwords...",
    "Enumerating SMB shares for vulnerabilities...",
    "Scanning for unpatched remote desktop services...",
    "Replaying captured session tokens to impersonate user...",
    "Generating rainbow tables for password cracking...",
    "Analyzing firmware to discover backdoor entry points...",
    "Decrypting PGP-encrypted emails with brute force...",
    "Triggering buffer overflow in legacy applications...",
    "Remotely disabling anti-malware systems...",
    "Compiling custom malware for targeted attacks...",
    "Monitoring unsecured IoT camera streams...",
    "Uploading persistent malicious scripts to servers...",
    "Downloading system configurations for analysis...",
    "Launching spear-phishing campaign...",
    "Injecting rogue software updates into CDN...",
    "Analyzing keystroke dynamics to mimic users...",
    "Hijacking network traffic for credit card skimming...",
    "Stealing cryptocurrency wallets from offline systems...",
    "Tampering with time-sensitive tokens for access...",
    "Jamming wireless frequencies for denial of service...",
    "Infiltrating supply chain software updates for attacks...",
    "Compromising unsecured VPN configurations...",
    "Embedding malware in hardware-level firmware...",
    "Initiating system-wide privilege escalation...",
    "Simulating advanced persistent threat (APT) activity...",
    "Cracking proprietary encryption with quantum algorithms...",
    "Deploying honey-pot decoy to lure hackers...",
    "Manipulating AI-driven defense systems for bypass...",
    "Detecting zero-day exploits in defense system logs...",
    "Mapping dark web markets for compromised assets...",
    "Sniffing raw traffic from wireless routers...",
    "Forcing firmware updates on compromised hardware...",
    "Analyzing machine learning models for data leaks...",
    "Bypassing hardware-level security mechanisms...",
    "Compiling user metadata from breached databases...",
    "Performing timing attacks to extract encryption keys...",
    "Exploiting firmware backdoors for remote access...",
    "Hijacking cellular signals for mobile data extraction..."
]

def AFakeHackPrank():
    while True:
        time.sleep(random.uniform(0.05, 0.5))
        yield random.choice(fake_hacking_prompts)

def BFakeHackPrank():
    for message in AFakeHackPrank():
        try:
            from colorama import Fore
        except ImportError:
            print("Module 'colorama' not found. Please install it.")
        yield Fore.GREEN + message


def FakeHackPrank():
    for msg in BFakeHackPrank():
        print(msg)

#FakeHackPrank()

import pygame as pg

class Button:
    def __init__(self, image_path, pos, scalew = 1.0, scaleh = 1.0):
        self.image = pg.image.load(image_path).convert_alpha()
        
        og_width = self.image.get_width()
        og_height = self.image.get_height()
        new_width = int(og_width * scalew)
        new_height = int(og_height * scaleh)
        self.image = pg.transform.scale(self.image, (new_width, new_height))
        
        self.rect = self.image.get_rect(topleft = pos)
        
    def draw(self, window):
        window.blit(self.image, self.rect)
        
    def is_pressed(self):
        mouse_pos = pg.mouse.get_pos()
        mouse_pressed = pg.mouse.get_pressed()[0]
        
        if self.rect.collidepoint(mouse_pos):
            if mouse_pressed:
                return True
        return False
    
    def move(self, pos):
        self.rect = self.image.get_rect(topleft = pos)
        
        
        
        